<?php

namespace PPE4\TobatBundle\Repository;

/**
 * reserverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reserverRepository extends \Doctrine\ORM\EntityRepository
{
}
