<?php

namespace PPE4\TobatBundle\Repository;

/**
 * TobatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TobatRepository extends \Doctrine\ORM\EntityRepository
{
}
